// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oopxazxddvdxhpolsoxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcHhhenhkZHZkeGhwb2xzb3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDU3NzcsImV4cCI6MjA3MzkyMTc3N30.UF1LfJxhLLvuk9eKwnxlTpOA5UAvgd1i_w0W2F2WJQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});